### PR TITLE
Feat add HM token tracking

### PR DESCRIPTION
**Pull request by boyin0x**
Solution to the Gitcoin bounty [Humansubgraph: Add Erc20 Support And Index Our Hmt Token Events](https://gitcoin.co/issue/28904)

- [x] Include HMToken in the subgraph (#9)
- [x] Track bulkTransfer events from Escrow contract. (#8)

Let me know if you want me to include any other information or changes.

### CODE REVIEW

**Comment by Human-Protocol** [comment]
Great, how did you test it?

**Comment by posix4e** [comment]
Testing live!

**Comment by posix4e** [comment]
merged for both matic and rinkeby

**Comment by posix4e** [comment]
@boyin0x Does https://thegraph.com/hosted-service/subgraph/posix4e/human-polygon?version=pending look right to you?

**Comment by posix4e** [comment]
and https://thegraph.com/hosted-service/subgraph/posix4e/humanrinkeby?selected=logs

**Comment by boyin0x** [comment]
Hi @Human-Protocol @posix4e , yes, I tested it here https://thegraph.com/hosted-service/subgraph/boyin0x/human-polygon and it looks right.

**Comment by ansaqib** [comment]
Hi @boyin0x,
Thanks for your contribution, are you on our [Discord server](https://discord.gg/HgeKvcYw) in our tech-discussion channel, also can we get on a [video chat](https://about.me/posix4e)

**Pull request merged**
